// Code generated by Lark OpenAPI.

package larkapplication

import (
	"context"
	"github.com/larksuite/oapi-sdk-go/v3/core"
	"net/http"
)

type V5 struct {
	Application *application // application
}

func New(config *larkcore.Config) *V5 {
	return &V5{
		Application: &application{config: config},
	}
}

type application struct {
	config *larkcore.Config
}

// Favourite
//
// -
//
// - 官网API文档链接:https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=favourite&project=application&resource=application&version=v5
//
// - 使用Demo链接:https://github.com/larksuite/oapi-sdk-go/tree/v3_main/sample/apiall/applicationv5/favourite_application.go
func (a *application) Favourite(ctx context.Context, req *FavouriteApplicationReq, options ...larkcore.RequestOptionFunc) (*FavouriteApplicationResp, error) {
	// 发起请求
	apiReq := req.apiReq
	apiReq.ApiPath = "/open-apis/application/v5/applications/favourite"
	apiReq.HttpMethod = http.MethodGet
	apiReq.SupportedAccessTokenTypes = []larkcore.AccessTokenType{larkcore.AccessTokenTypeUser}
	apiResp, err := larkcore.Request(ctx, apiReq, a.config, options...)
	if err != nil {
		return nil, err
	}
	// 反序列响应结果
	resp := &FavouriteApplicationResp{ApiResp: apiResp}
	err = apiResp.JSONUnmarshalBody(resp, a.config)
	if err != nil {
		return nil, err
	}
	return resp, err
}
func (a *application) FavouriteByIterator(ctx context.Context, req *FavouriteApplicationReq, options ...larkcore.RequestOptionFunc) (*FavouriteApplicationIterator, error) {
	return &FavouriteApplicationIterator{
		ctx:      ctx,
		req:      req,
		listFunc: a.Favourite,
		options:  options,
		limit:    req.Limit}, nil
}

// Recommend
//
// -
//
// - 官网API文档链接:https://open.feishu.cn/api-explorer?from=op_doc_tab&apiName=recommend&project=application&resource=application&version=v5
//
// - 使用Demo链接:https://github.com/larksuite/oapi-sdk-go/tree/v3_main/sample/apiall/applicationv5/recommend_application.go
func (a *application) Recommend(ctx context.Context, req *RecommendApplicationReq, options ...larkcore.RequestOptionFunc) (*RecommendApplicationResp, error) {
	// 发起请求
	apiReq := req.apiReq
	apiReq.ApiPath = "/open-apis/application/v5/applications/recommend"
	apiReq.HttpMethod = http.MethodGet
	apiReq.SupportedAccessTokenTypes = []larkcore.AccessTokenType{larkcore.AccessTokenTypeUser}
	apiResp, err := larkcore.Request(ctx, apiReq, a.config, options...)
	if err != nil {
		return nil, err
	}
	// 反序列响应结果
	resp := &RecommendApplicationResp{ApiResp: apiResp}
	err = apiResp.JSONUnmarshalBody(resp, a.config)
	if err != nil {
		return nil, err
	}
	return resp, err
}
func (a *application) RecommendByIterator(ctx context.Context, req *RecommendApplicationReq, options ...larkcore.RequestOptionFunc) (*RecommendApplicationIterator, error) {
	return &RecommendApplicationIterator{
		ctx:      ctx,
		req:      req,
		listFunc: a.Recommend,
		options:  options,
		limit:    req.Limit}, nil
}
