// Code generated by lark suite oapi sdk gen
package v1

import (
	"github.com/larksuite/oapi-sdk-go/event/core/model"
)

type UserId struct {
	OpenId string `json:"open_id,omitempty"`
	UserId string `json:"user_id,omitempty"`
}

type AppOpenEventData struct {
	AppId      string    `json:"app_id,omitempty"`
	TenantKey  string    `json:"tenant_key,omitempty"`
	Type       string    `json:"type,omitempty"`
	Applicants []*UserId `json:"applicants,omitempty"`
	Installer  *UserId   `json:"installer,omitempty"`
}

type AppOpenEvent struct {
	*model.BaseEvent
	Event *AppOpenEventData `json:"event"`
}

type AppStatusChangeEventData struct {
	AppId     string `json:"app_id,omitempty"`
	TenantKey string `json:"tenant_key,omitempty"`
	Type      string `json:"type,omitempty"`
	Status    string `json:"status,omitempty"`
}

type AppStatusChangeEvent struct {
	*model.BaseEvent
	Event *AppStatusChangeEventData `json:"event"`
}

type AppUninstalledEventData struct {
	AppId     string `json:"app_id,omitempty"`
	TenantKey string `json:"tenant_key,omitempty"`
	Type      string `json:"type,omitempty"`
}

type AppUninstalledEvent struct {
	*model.BaseEvent
	Event *AppUninstalledEventData `json:"event"`
}

type OrderPaidEventData struct {
	AppId         string `json:"app_id,omitempty"`
	TenantKey     string `json:"tenant_key,omitempty"`
	Type          string `json:"type,omitempty"`
	OrderId       string `json:"order_id,omitempty"`
	PricePlanId   string `json:"price_plan_id,omitempty"`
	PricePlanType string `json:"price_plan_type,omitempty"`
	Seats         int    `json:"seats,omitempty"`
	BuyCount      int    `json:"buy_count,omitempty"`
	CreateTime    string `json:"create_time,omitempty"`
	PayTime       string `json:"pay_time,omitempty"`
	BuyType       string `json:"buy_type,omitempty"`
	SrcOrderId    string `json:"src_order_id,omitempty"`
	OrderPayPrice int    `json:"order_pay_price,omitempty"`
}

type OrderPaidEvent struct {
	*model.BaseEvent
	Event *OrderPaidEventData `json:"event"`
}
