// Package dispatcher code generated by oapi sdk gen
package dispatcher

import (
	"context"
	"github.com/larksuite/oapi-sdk-go/service/attendance/v1"
)

func (dispatcher *EventReqDispatcher) OnUserFlowCreatedV1(handler func(ctx context.Context, event *attendance.UserFlowCreatedEvent) error) *EventReqDispatcher {
	dispatcher.eventType2EventHandler["attendance.user_flow.created_v1"] = attendance.NewUserFlowCreatedEventHandler(handler)
	return dispatcher
}
func (dispatcher *EventReqDispatcher) OnUserTaskUpdatedV1(handler func(ctx context.Context, event *attendance.UserTaskUpdatedEvent) error) *EventReqDispatcher {
	dispatcher.eventType2EventHandler["attendance.user_task.updated_v1"] = attendance.NewUserTaskUpdatedEventHandler(handler)
	return dispatcher
}
