// Package wiki code generated by oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package larkwiki

import (
	"fmt"

	"context"
	"errors"

	"github.com/larksuite/oapi-sdk-go/v3/core"
)

type AuthInfo struct {
	SessionKey *string `json:"session_key,omitempty"` // $ session key

	UserId *string `json:"user_id,omitempty"` // $ feishu id for internal app.

	OpenAppId *string `json:"open_app_id,omitempty"` // $ app id of open platform.

	Region *string `json:"region,omitempty"` // $ user account region. cn for china; va for oversea

	OpenBotId *string `json:"open_bot_id,omitempty"` // $ open bot id

	BotId *string `json:"bot_id,omitempty"` // $ bot id

	AuthType *string `json:"auth_type,omitempty"` // $ 鉴权类型: LarkSession, TenantAccessToken, UserAccessToken, OpenSession等

	Extra map[string]string `json:"extra,omitempty"` //
}

type AuthInfoBuilder struct {
	sessionKey    string // $ session key
	sessionKeySet bool

	userId    string // $ feishu id for internal app.
	userIdSet bool

	openAppId    string // $ app id of open platform.
	openAppIdSet bool

	region    string // $ user account region. cn for china; va for oversea
	regionSet bool

	openBotId    string // $ open bot id
	openBotIdSet bool

	botId    string // $ bot id
	botIdSet bool

	authType    string // $ 鉴权类型: LarkSession, TenantAccessToken, UserAccessToken, OpenSession等
	authTypeSet bool

	extra    map[string]string //
	extraSet bool
}

func NewAuthInfoBuilder() *AuthInfoBuilder {
	builder := &AuthInfoBuilder{}
	return builder
}

// $ session key
//
// 示例值：
func (builder *AuthInfoBuilder) SessionKey(sessionKey string) *AuthInfoBuilder {
	builder.sessionKey = sessionKey
	builder.sessionKeySet = true
	return builder
}

// $ feishu id for internal app.
//
// 示例值：
func (builder *AuthInfoBuilder) UserId(userId string) *AuthInfoBuilder {
	builder.userId = userId
	builder.userIdSet = true
	return builder
}

// $ app id of open platform.
//
// 示例值：
func (builder *AuthInfoBuilder) OpenAppId(openAppId string) *AuthInfoBuilder {
	builder.openAppId = openAppId
	builder.openAppIdSet = true
	return builder
}

// $ user account region. cn for china; va for oversea
//
// 示例值：
func (builder *AuthInfoBuilder) Region(region string) *AuthInfoBuilder {
	builder.region = region
	builder.regionSet = true
	return builder
}

// $ open bot id
//
// 示例值：
func (builder *AuthInfoBuilder) OpenBotId(openBotId string) *AuthInfoBuilder {
	builder.openBotId = openBotId
	builder.openBotIdSet = true
	return builder
}

// $ bot id
//
// 示例值：
func (builder *AuthInfoBuilder) BotId(botId string) *AuthInfoBuilder {
	builder.botId = botId
	builder.botIdSet = true
	return builder
}

// $ 鉴权类型: LarkSession, TenantAccessToken, UserAccessToken, OpenSession等
//
// 示例值：
func (builder *AuthInfoBuilder) AuthType(authType string) *AuthInfoBuilder {
	builder.authType = authType
	builder.authTypeSet = true
	return builder
}

// 示例值：
func (builder *AuthInfoBuilder) Extra(extra map[string]string) *AuthInfoBuilder {
	builder.extra = extra
	builder.extraSet = true
	return builder
}

func (builder *AuthInfoBuilder) Build() *AuthInfo {
	req := &AuthInfo{}
	if builder.sessionKeySet {
		req.SessionKey = &builder.sessionKey

	}
	if builder.userIdSet {
		req.UserId = &builder.userId

	}
	if builder.openAppIdSet {
		req.OpenAppId = &builder.openAppId

	}
	if builder.regionSet {
		req.Region = &builder.region

	}
	if builder.openBotIdSet {
		req.OpenBotId = &builder.openBotId

	}
	if builder.botIdSet {
		req.BotId = &builder.botId

	}
	if builder.authTypeSet {
		req.AuthType = &builder.authType

	}
	if builder.extraSet {
		req.Extra = builder.extra
	}
	return req
}

type ClientInfo struct {
	ClientIp *string `json:"client_ip,omitempty"` // 1: optional string Platform (gw.ctx="mw_platform"); //$ depracated 请求的平台\n2: optional string LarkVersion (gw.ctx="mw_lark_version"); //$ depracated 如果是来自Feisu, 这里是飞书的Version\n3: optional AppForm AppForm (gw.ctx="mw_app_form"); //$ depracated 应用形态 1-小程序\n4: optional string AppVersion (gw.ctx="mw_app_version"); //$ depracated 应用版本\n5: optional string OS (gw.ctx="mw_os"); //$ depracated 操作系统\n$ 客户端IP
}

type ClientInfoBuilder struct {
	clientIp    string // 1: optional string Platform (gw.ctx="mw_platform"); //$ depracated 请求的平台\n2: optional string LarkVersion (gw.ctx="mw_lark_version"); //$ depracated 如果是来自Feisu, 这里是飞书的Version\n3: optional AppForm AppForm (gw.ctx="mw_app_form"); //$ depracated 应用形态 1-小程序\n4: optional string AppVersion (gw.ctx="mw_app_version"); //$ depracated 应用版本\n5: optional string OS (gw.ctx="mw_os"); //$ depracated 操作系统\n$ 客户端IP
	clientIpSet bool
}

func NewClientInfoBuilder() *ClientInfoBuilder {
	builder := &ClientInfoBuilder{}
	return builder
}

// 1: optional string Platform (gw.ctx="mw_platform"); //$ depracated 请求的平台\n2: optional string LarkVersion (gw.ctx="mw_lark_version"); //$ depracated 如果是来自Feisu, 这里是飞书的Version\n3: optional AppForm AppForm (gw.ctx="mw_app_form"); //$ depracated 应用形态 1-小程序\n4: optional string AppVersion (gw.ctx="mw_app_version"); //$ depracated 应用版本\n5: optional string OS (gw.ctx="mw_os"); //$ depracated 操作系统\n$ 客户端IP
//
// 示例值：
func (builder *ClientInfoBuilder) ClientIp(clientIp string) *ClientInfoBuilder {
	builder.clientIp = clientIp
	builder.clientIpSet = true
	return builder
}

func (builder *ClientInfoBuilder) Build() *ClientInfo {
	req := &ClientInfo{}
	if builder.clientIpSet {
		req.ClientIp = &builder.clientIp

	}
	return req
}

type DepartmentId struct {
	DepartmentId *string `json:"department_id,omitempty"` //

	OpenDepartmentId *string `json:"open_department_id,omitempty"` //
}

type DepartmentIdBuilder struct {
	departmentId    string //
	departmentIdSet bool

	openDepartmentId    string //
	openDepartmentIdSet bool
}

func NewDepartmentIdBuilder() *DepartmentIdBuilder {
	builder := &DepartmentIdBuilder{}
	return builder
}

// 示例值：
func (builder *DepartmentIdBuilder) DepartmentId(departmentId string) *DepartmentIdBuilder {
	builder.departmentId = departmentId
	builder.departmentIdSet = true
	return builder
}

// 示例值：
func (builder *DepartmentIdBuilder) OpenDepartmentId(openDepartmentId string) *DepartmentIdBuilder {
	builder.openDepartmentId = openDepartmentId
	builder.openDepartmentIdSet = true
	return builder
}

func (builder *DepartmentIdBuilder) Build() *DepartmentId {
	req := &DepartmentId{}
	if builder.departmentIdSet {
		req.DepartmentId = &builder.departmentId

	}
	if builder.openDepartmentIdSet {
		req.OpenDepartmentId = &builder.openDepartmentId

	}
	return req
}

type Head struct {
	Id *string `json:"id,omitempty"` // 请求方的id deprecated

	TenantId *string `json:"tenant_id,omitempty"` // 请求方的组织，在多租户业务中使用

	AppId *string `json:"app_id,omitempty"` // 请求方的appid

	OpenId *string `json:"open_id,omitempty"` // 开放平台的OpenID

	TenantKey *string `json:"tenant_key,omitempty"` // 如果小程序登录，这个是原始的信息，和OpenID是一个意思

	Auth *AuthInfo `json:"auth,omitempty"` // thrift --gen go idl/common.thrift

	Fields map[string]string `json:"fields,omitempty"` // $ plugin output

	Env *string `json:"env,omitempty"` // Header的环境

	Locale *string `json:"locale,omitempty"` // 200: optional HttpHeader HttpHeader (api.json="HttpHeader"), //$ 从HttpHeader透传的HttpHeader\n$ 所在区域，参考:https://zh.wikipedia.org/wiki/%E5%8C%BA%E5%9F%9F%E8%AE%BE%E7%BD%AE的简称

	Client *ClientInfo `json:"client,omitempty"` // $ 客户端信息
}

type HeadBuilder struct {
	id    string // 请求方的id deprecated
	idSet bool

	tenantId    string // 请求方的组织，在多租户业务中使用
	tenantIdSet bool

	appId    string // 请求方的appid
	appIdSet bool

	openId    string // 开放平台的OpenID
	openIdSet bool

	tenantKey    string // 如果小程序登录，这个是原始的信息，和OpenID是一个意思
	tenantKeySet bool

	auth    *AuthInfo // thrift --gen go idl/common.thrift
	authSet bool

	fields    map[string]string // $ plugin output
	fieldsSet bool

	env    string // Header的环境
	envSet bool

	locale    string // 200: optional HttpHeader HttpHeader (api.json="HttpHeader"), //$ 从HttpHeader透传的HttpHeader\n$ 所在区域，参考:https://zh.wikipedia.org/wiki/%E5%8C%BA%E5%9F%9F%E8%AE%BE%E7%BD%AE的简称
	localeSet bool

	client    *ClientInfo // $ 客户端信息
	clientSet bool
}

func NewHeadBuilder() *HeadBuilder {
	builder := &HeadBuilder{}
	return builder
}

// 请求方的id deprecated
//
// 示例值：
func (builder *HeadBuilder) Id(id string) *HeadBuilder {
	builder.id = id
	builder.idSet = true
	return builder
}

// 请求方的组织，在多租户业务中使用
//
// 示例值：
func (builder *HeadBuilder) TenantId(tenantId string) *HeadBuilder {
	builder.tenantId = tenantId
	builder.tenantIdSet = true
	return builder
}

// 请求方的appid
//
// 示例值：
func (builder *HeadBuilder) AppId(appId string) *HeadBuilder {
	builder.appId = appId
	builder.appIdSet = true
	return builder
}

// 开放平台的OpenID
//
// 示例值：
func (builder *HeadBuilder) OpenId(openId string) *HeadBuilder {
	builder.openId = openId
	builder.openIdSet = true
	return builder
}

// 如果小程序登录，这个是原始的信息，和OpenID是一个意思
//
// 示例值：
func (builder *HeadBuilder) TenantKey(tenantKey string) *HeadBuilder {
	builder.tenantKey = tenantKey
	builder.tenantKeySet = true
	return builder
}

// thrift --gen go idl/common.thrift
//
// 示例值：
func (builder *HeadBuilder) Auth(auth *AuthInfo) *HeadBuilder {
	builder.auth = auth
	builder.authSet = true
	return builder
}

// $ plugin output
//
// 示例值：
func (builder *HeadBuilder) Fields(fields map[string]string) *HeadBuilder {
	builder.fields = fields
	builder.fieldsSet = true
	return builder
}

// Header的环境
//
// 示例值：
func (builder *HeadBuilder) Env(env string) *HeadBuilder {
	builder.env = env
	builder.envSet = true
	return builder
}

// 200: optional HttpHeader HttpHeader (api.json="HttpHeader"), //$ 从HttpHeader透传的HttpHeader\n$ 所在区域，参考:https://zh.wikipedia.org/wiki/%E5%8C%BA%E5%9F%9F%E8%AE%BE%E7%BD%AE的简称
//
// 示例值：
func (builder *HeadBuilder) Locale(locale string) *HeadBuilder {
	builder.locale = locale
	builder.localeSet = true
	return builder
}

// $ 客户端信息
//
// 示例值：
func (builder *HeadBuilder) Client(client *ClientInfo) *HeadBuilder {
	builder.client = client
	builder.clientSet = true
	return builder
}

func (builder *HeadBuilder) Build() *Head {
	req := &Head{}
	if builder.idSet {
		req.Id = &builder.id

	}
	if builder.tenantIdSet {
		req.TenantId = &builder.tenantId

	}
	if builder.appIdSet {
		req.AppId = &builder.appId

	}
	if builder.openIdSet {
		req.OpenId = &builder.openId

	}
	if builder.tenantKeySet {
		req.TenantKey = &builder.tenantKey

	}
	if builder.authSet {
		req.Auth = builder.auth
	}
	if builder.fieldsSet {
		req.Fields = builder.fields
	}
	if builder.envSet {
		req.Env = &builder.env

	}
	if builder.localeSet {
		req.Locale = &builder.locale

	}
	if builder.clientSet {
		req.Client = builder.client
	}
	return req
}

type Node struct {
	NodeId *string `json:"node_id,omitempty"` // node的唯一标识

	SpaceId *string `json:"space_id,omitempty"` // 所属空间id

	ParentId *string `json:"parent_id,omitempty"` // 父节点id

	ObjType *int `json:"obj_type,omitempty"` // 对应的obj类型

	Title *string `json:"title,omitempty"` // 名称

	Url *string `json:"url,omitempty"` // 路径

	Icon *string `json:"icon,omitempty"` // icon

	AreaId *string `json:"area_id,omitempty"` // 所属权限范围id

	SortId *float64 `json:"sort_id,omitempty"` // 序号

	Domain *string `json:"domain,omitempty"` // 所在域名

	ObjToken *string `json:"obj_token,omitempty"` // objToken

	CreateTime *string `json:"create_time,omitempty"` // 创建时间

	UpdateTime *string `json:"update_time,omitempty"` // 更新时间

	DeleteTime *string `json:"delete_time,omitempty"` // 删除时间

	ChildNum *int `json:"child_num,omitempty"` // 子节点数

	Version *int `json:"version,omitempty"` // 版本号
}

type NodeBuilder struct {
	nodeId    string // node的唯一标识
	nodeIdSet bool

	spaceId    string // 所属空间id
	spaceIdSet bool

	parentId    string // 父节点id
	parentIdSet bool

	objType    int // 对应的obj类型
	objTypeSet bool

	title    string // 名称
	titleSet bool

	url    string // 路径
	urlSet bool

	icon    string // icon
	iconSet bool

	areaId    string // 所属权限范围id
	areaIdSet bool

	sortId    float64 // 序号
	sortIdSet bool

	domain    string // 所在域名
	domainSet bool

	objToken    string // objToken
	objTokenSet bool

	createTime    string // 创建时间
	createTimeSet bool

	updateTime    string // 更新时间
	updateTimeSet bool

	deleteTime    string // 删除时间
	deleteTimeSet bool

	childNum    int // 子节点数
	childNumSet bool

	version    int // 版本号
	versionSet bool
}

func NewNodeBuilder() *NodeBuilder {
	builder := &NodeBuilder{}
	return builder
}

// node的唯一标识
//
// 示例值：
func (builder *NodeBuilder) NodeId(nodeId string) *NodeBuilder {
	builder.nodeId = nodeId
	builder.nodeIdSet = true
	return builder
}

// 所属空间id
//
// 示例值：
func (builder *NodeBuilder) SpaceId(spaceId string) *NodeBuilder {
	builder.spaceId = spaceId
	builder.spaceIdSet = true
	return builder
}

// 父节点id
//
// 示例值：
func (builder *NodeBuilder) ParentId(parentId string) *NodeBuilder {
	builder.parentId = parentId
	builder.parentIdSet = true
	return builder
}

// 对应的obj类型
//
// 示例值：
func (builder *NodeBuilder) ObjType(objType int) *NodeBuilder {
	builder.objType = objType
	builder.objTypeSet = true
	return builder
}

// 名称
//
// 示例值：
func (builder *NodeBuilder) Title(title string) *NodeBuilder {
	builder.title = title
	builder.titleSet = true
	return builder
}

// 路径
//
// 示例值：
func (builder *NodeBuilder) Url(url string) *NodeBuilder {
	builder.url = url
	builder.urlSet = true
	return builder
}

// icon
//
// 示例值：
func (builder *NodeBuilder) Icon(icon string) *NodeBuilder {
	builder.icon = icon
	builder.iconSet = true
	return builder
}

// 所属权限范围id
//
// 示例值：
func (builder *NodeBuilder) AreaId(areaId string) *NodeBuilder {
	builder.areaId = areaId
	builder.areaIdSet = true
	return builder
}

// 序号
//
// 示例值：
func (builder *NodeBuilder) SortId(sortId float64) *NodeBuilder {
	builder.sortId = sortId
	builder.sortIdSet = true
	return builder
}

// 所在域名
//
// 示例值：
func (builder *NodeBuilder) Domain(domain string) *NodeBuilder {
	builder.domain = domain
	builder.domainSet = true
	return builder
}

// objToken
//
// 示例值：
func (builder *NodeBuilder) ObjToken(objToken string) *NodeBuilder {
	builder.objToken = objToken
	builder.objTokenSet = true
	return builder
}

// 创建时间
//
// 示例值：
func (builder *NodeBuilder) CreateTime(createTime string) *NodeBuilder {
	builder.createTime = createTime
	builder.createTimeSet = true
	return builder
}

// 更新时间
//
// 示例值：
func (builder *NodeBuilder) UpdateTime(updateTime string) *NodeBuilder {
	builder.updateTime = updateTime
	builder.updateTimeSet = true
	return builder
}

// 删除时间
//
// 示例值：
func (builder *NodeBuilder) DeleteTime(deleteTime string) *NodeBuilder {
	builder.deleteTime = deleteTime
	builder.deleteTimeSet = true
	return builder
}

// 子节点数
//
// 示例值：
func (builder *NodeBuilder) ChildNum(childNum int) *NodeBuilder {
	builder.childNum = childNum
	builder.childNumSet = true
	return builder
}

// 版本号
//
// 示例值：
func (builder *NodeBuilder) Version(version int) *NodeBuilder {
	builder.version = version
	builder.versionSet = true
	return builder
}

func (builder *NodeBuilder) Build() *Node {
	req := &Node{}
	if builder.nodeIdSet {
		req.NodeId = &builder.nodeId

	}
	if builder.spaceIdSet {
		req.SpaceId = &builder.spaceId

	}
	if builder.parentIdSet {
		req.ParentId = &builder.parentId

	}
	if builder.objTypeSet {
		req.ObjType = &builder.objType

	}
	if builder.titleSet {
		req.Title = &builder.title

	}
	if builder.urlSet {
		req.Url = &builder.url

	}
	if builder.iconSet {
		req.Icon = &builder.icon

	}
	if builder.areaIdSet {
		req.AreaId = &builder.areaId

	}
	if builder.sortIdSet {
		req.SortId = &builder.sortId

	}
	if builder.domainSet {
		req.Domain = &builder.domain

	}
	if builder.objTokenSet {
		req.ObjToken = &builder.objToken

	}
	if builder.createTimeSet {
		req.CreateTime = &builder.createTime

	}
	if builder.updateTimeSet {
		req.UpdateTime = &builder.updateTime

	}
	if builder.deleteTimeSet {
		req.DeleteTime = &builder.deleteTime

	}
	if builder.childNumSet {
		req.ChildNum = &builder.childNum

	}
	if builder.versionSet {
		req.Version = &builder.version

	}
	return req
}

type SearchNodeReqBodyBuilder struct {
	query    string // 搜索关键词
	querySet bool

	spaceId    string // 文档所属的知识空间ID，为空搜索所有 wiki
	spaceIdSet bool

	nodeId    string // wiki token，不为空搜索该节点及其所有子节点，为空搜索所有 wiki（根据 space_id 选择 space）
	nodeIdSet bool
}

func NewSearchNodeReqBodyBuilder() *SearchNodeReqBodyBuilder {
	builder := &SearchNodeReqBodyBuilder{}
	return builder
}

// 搜索关键词
//
// 示例值：123
func (builder *SearchNodeReqBodyBuilder) Query(query string) *SearchNodeReqBodyBuilder {
	builder.query = query
	builder.querySet = true
	return builder
}

// 文档所属的知识空间ID，为空搜索所有 wiki
//
// 示例值：6967549310762221587
func (builder *SearchNodeReqBodyBuilder) SpaceId(spaceId string) *SearchNodeReqBodyBuilder {
	builder.spaceId = spaceId
	builder.spaceIdSet = true
	return builder
}

// wiki token，不为空搜索该节点及其所有子节点，为空搜索所有 wiki（根据 space_id 选择 space）
//
// 示例值：O5UIw9NA8iW308kQQeybWLZqcXc
func (builder *SearchNodeReqBodyBuilder) NodeId(nodeId string) *SearchNodeReqBodyBuilder {
	builder.nodeId = nodeId
	builder.nodeIdSet = true
	return builder
}

func (builder *SearchNodeReqBodyBuilder) Build() *SearchNodeReqBody {
	req := &SearchNodeReqBody{}
	if builder.querySet {
		req.Query = &builder.query
	}
	if builder.spaceIdSet {
		req.SpaceId = &builder.spaceId
	}
	if builder.nodeIdSet {
		req.NodeId = &builder.nodeId
	}
	return req
}

type SearchNodePathReqBodyBuilder struct {
	query      string
	querySet   bool
	spaceId    string
	spaceIdSet bool
	nodeId     string
	nodeIdSet  bool
}

func NewSearchNodePathReqBodyBuilder() *SearchNodePathReqBodyBuilder {
	builder := &SearchNodePathReqBodyBuilder{}
	return builder
}

// 搜索关键词
//
// 示例值：123
func (builder *SearchNodePathReqBodyBuilder) Query(query string) *SearchNodePathReqBodyBuilder {
	builder.query = query
	builder.querySet = true
	return builder
}

// 文档所属的知识空间ID，为空搜索所有 wiki
//
// 示例值：6967549310762221587
func (builder *SearchNodePathReqBodyBuilder) SpaceId(spaceId string) *SearchNodePathReqBodyBuilder {
	builder.spaceId = spaceId
	builder.spaceIdSet = true
	return builder
}

// wiki token，不为空搜索该节点及其所有子节点，为空搜索所有 wiki（根据 space_id 选择 space）
//
// 示例值：O5UIw9NA8iW308kQQeybWLZqcXc
func (builder *SearchNodePathReqBodyBuilder) NodeId(nodeId string) *SearchNodePathReqBodyBuilder {
	builder.nodeId = nodeId
	builder.nodeIdSet = true
	return builder
}

func (builder *SearchNodePathReqBodyBuilder) Build() (*SearchNodeReqBody, error) {
	req := &SearchNodeReqBody{}
	if builder.querySet {
		req.Query = &builder.query
	}
	if builder.spaceIdSet {
		req.SpaceId = &builder.spaceId
	}
	if builder.nodeIdSet {
		req.NodeId = &builder.nodeId
	}
	return req, nil
}

type SearchNodeReqBuilder struct {
	apiReq *larkcore.ApiReq
	body   *SearchNodeReqBody
	limit  int // 最大返回多少记录，当使用迭代器访问时才有效
}

func NewSearchNodeReqBuilder() *SearchNodeReqBuilder {
	builder := &SearchNodeReqBuilder{}
	builder.apiReq = &larkcore.ApiReq{
		PathParams:  larkcore.PathParams{},
		QueryParams: larkcore.QueryParams{},
	}
	return builder
}

// 最大返回多少记录，当使用迭代器访问时才有效
func (builder *SearchNodeReqBuilder) Limit(limit int) *SearchNodeReqBuilder {
	builder.limit = limit
	return builder
}

// 示例值：
func (builder *SearchNodeReqBuilder) PageToken(pageToken string) *SearchNodeReqBuilder {
	builder.apiReq.QueryParams.Set("page_token", fmt.Sprint(pageToken))
	return builder
}

// 示例值：
func (builder *SearchNodeReqBuilder) PageSize(pageSize int) *SearchNodeReqBuilder {
	builder.apiReq.QueryParams.Set("page_size", fmt.Sprint(pageSize))
	return builder
}

func (builder *SearchNodeReqBuilder) Body(body *SearchNodeReqBody) *SearchNodeReqBuilder {
	builder.body = body
	return builder
}

func (builder *SearchNodeReqBuilder) Build() *SearchNodeReq {
	req := &SearchNodeReq{}
	req.apiReq = &larkcore.ApiReq{}
	req.Limit = builder.limit
	req.apiReq.QueryParams = builder.apiReq.QueryParams
	req.apiReq.Body = builder.body
	return req
}

type SearchNodeReqBody struct {
	Query *string `json:"query,omitempty"` // 搜索关键词

	SpaceId *string `json:"space_id,omitempty"` // 文档所属的知识空间ID，为空搜索所有 wiki

	NodeId *string `json:"node_id,omitempty"` // wiki token，不为空搜索该节点及其所有子节点，为空搜索所有 wiki（根据 space_id 选择 space）
}

type SearchNodeReq struct {
	apiReq *larkcore.ApiReq
	Body   *SearchNodeReqBody `body:""`
	Limit  int                // 最多返回多少记录，只有在使用迭代器访问时，才有效

}

type SearchNodeRespData struct {
	Items []*Node `json:"items,omitempty"` // 搜索到 wiki

	PageToken *string `json:"page_token,omitempty"` // 翻页 token，传入返回下一页，首页不需要传入

	HasMore *bool `json:"has_more,omitempty"` // 是否还有下一页
}

type SearchNodeResp struct {
	*larkcore.ApiResp `json:"-"`
	larkcore.CodeError
	Data *SearchNodeRespData `json:"data"` // 业务数据
}

func (resp *SearchNodeResp) Success() bool {
	return resp.Code == 0
}

type SearchNodeIterator struct {
	nextPageToken *string
	items         []*Node
	index         int
	limit         int
	ctx           context.Context
	req           *SearchNodeReq
	listFunc      func(ctx context.Context, req *SearchNodeReq, options ...larkcore.RequestOptionFunc) (*SearchNodeResp, error)
	options       []larkcore.RequestOptionFunc
	curlNum       int
}

func (iterator *SearchNodeIterator) Next() (bool, *Node, error) {
	// 达到最大量，则返回
	if iterator.limit > 0 && iterator.curlNum >= iterator.limit {
		return false, nil, nil
	}

	// 为0则拉取数据
	if iterator.index == 0 || iterator.index >= len(iterator.items) {
		if iterator.index != 0 && iterator.nextPageToken == nil {
			return false, nil, nil
		}
		if iterator.nextPageToken != nil {
			iterator.req.apiReq.QueryParams.Set("page_token", *iterator.nextPageToken)
		}
		resp, err := iterator.listFunc(iterator.ctx, iterator.req, iterator.options...)
		if err != nil {
			return false, nil, err
		}

		if resp.Code != 0 {
			return false, nil, errors.New(fmt.Sprintf("Code:%d,Msg:%s", resp.Code, resp.Msg))
		}

		if len(resp.Data.Items) == 0 {
			return false, nil, nil
		}

		iterator.nextPageToken = resp.Data.PageToken
		iterator.items = resp.Data.Items
		iterator.index = 0
	}

	block := iterator.items[iterator.index]
	iterator.index++
	iterator.curlNum++
	return true, block, nil
}

func (iterator *SearchNodeIterator) NextPageToken() *string {
	return iterator.nextPageToken
}
